#!/bin/bash

# Run batch processes for insitu_stats library


global_size=( 4 8 16 32 64 128 256)
local_size=( 4 8 16 32 64 128 256)


run_command="mpiexec"
run_file="./3D_Grid"
out_file="run_results.txt"

make
rm $out_file
touch $out_file

let "count= 0"
# Run file and write to stdout and to file
for i in "${local_size[@]}"
do
  l_param=$(echo "-l $i/x$i/x$i" | tr -d "/")
  
  for j in "${global_size[@]}"
  do 
    g_param=$(echo "-g $j/x$j/x$j" | tr -d "/")
    let "div= $j / $i"
    if [ $div -gt 0 ]; then
      let "num= $div * $div * $div"
      num_proc="-n $num"
      let "count+=1"
      #echo "*******RUN $count **********" >> $out_file
      echo "******* RUN:$count: **************" | sudo tee -a $out_file
      #echo "*****Processors: $num*******" >> $out_file
      echo "***** Processors:$num: *********" | sudo tee -a $out_file
      #echo "$run_command $num_proc $run_file $g_param $l_param | tee /A $out_file"

      #$run_command $num_proc $run_file $g_param $l_param >> $out_file
      $run_command $num_proc $run_file $g_param $l_param | sudo tee -a $out_file
    fi
  done
done
